# Left thumb-stick up/down for velocity
# Right thumb-stick for steering
#
#    AXIS        Value
# Right Horiz.      0
# Right Vert.       1
# Left Horiz.     3
# Left Vert.      2

joy_teleop/teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.4
    scale_linear_turbo:
      x: 1.0
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.6
    scale_angular_turbo:
      yaw: 1.2
    enable_button: 5
    enable_turbo_button: -1
joy_teleop/joy_node:
  ros__parameters:
    deadzone: 0.1
    autorepeat_rate: 20.0
    dev: /dev/input/f710
