navsat_transform_node:
  ros__parameters:
    #odom_frame: odom
    #base_link_frame: base_link
    #world_frame: odom

    magnetic_declination_radians: 0
    yaw_offset: 0
    #zero_altitude: true
    
    broadcast_utm_transform: false
    publish_filtered_gps: false
